### ISSUE TITLE
Ultrasonic timer

### ISSUE THREAD

**Issue by AlchemicRonin** [illini-robomaster/iRM_Embedded_2022#16]
In ultrasonic example program, we use htim2. But actually in bsp_os, there is a wrapper function can be used to get time instead of calling htim2->CNT directly. We can see imu example as reference (like `bsp::SetHighresClockTimer(&htim2)`).

**Comment by 0-EricZhou-0** [comment]
Do we still need to do this? I see a newer issue says that we should change the ultrasonic logic from pooling to interrupt-driven.
