### ISSUE TITLE
K2, Q2, M2 is not usable in IOC as output gpio, only L2 works

### ISSUE THREAD

**Issue by AlchemicRonin** [illini-robomaster/iRM_Embedded_2022#23]
K2, Q2, M2 is not usable in IOC as output gpio, only L2 works

**Comment by 0-EricZhou-0** [comment]
I have tested pins K1, K2, M1, M2, L1, L2 just now using the ultrasonic sensor example and I can confirm they are usable.
Did you forget to do the tests with external battery?
